### ISSUE TITLE
Question about "Return Everything"?

### ISSUE THREAD

**Issue by XiaofengXie16** [haskellcamargo/js-real-world-functional-programming#5]
In the `Return everything` section, you put an example of calculating factorial
```
const fact = n => n === 0
    ? 1
    : n * fact(n - 1)

console.log('Fact of 5: ', fact(5))
```
With this approach, we will potentially get a stack overflow error , if the number gets large because of recursion and I would love to know what's your thought on this. Other than that, I learned a lot from your repo and thank you for putting these things together.

**Comment by cuchi** [comment]
In natively functional and some other languages, recursive calls are automatically optimized by the compiler, so we don't need to worry about the stack size. In order to be optimized, your recursion call should follow some rules to match the compiler criteria, like a [tail-call](https://en.wikipedia.org/wiki/Tail_call), for example.

JavaScript [does not support it in all platforms yet](https://stackoverflow.com/questions/37224520/are-functions-in-javascript-tail-call-optimized), maybe that's because the language a big dynamic mess.

**Comment by XiaofengXie16** [comment]
@cuchi Thanks for the explanation.
